In [1]:
import numpy as np

## DataTypes & Attributes 

In [2]:
# NumPy's main datatype is ndarray
a1 = np.array([1,2,3])
a1

array([1, 2, 3])

In [3]:
type(a1)

numpy.ndarray

In [4]:
a2 = np.array([[1,2,3], 
              [4,5,6]])
a3 = np.array([
    [
        [1,2,3], 
        [4,5,6],
        [7,8,9]
    ],
    [
        [10,11,12], 
        [13,14,15],
        [16,17,18]
    ]
])
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [5]:
a3.shape

(2, 3, 3)

In [6]:
a3.ndim

3

In [7]:
a3.dtype

dtype('int32')

In [8]:
# Create a dataframe from numpy array
import pandas as pd
df = pd.DataFrame(a2)
df

0  1  2
0  1  2  3
1  4  5  6

## 2. create arrays

In [9]:
sample_array = np.array([1,2,3])
sample_array

array([1, 2, 3])

In [10]:
sample_array.dtype

dtype('int32')

In [11]:
ones = np.ones((2,3))
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [12]:
ones.dtype

dtype('float64')

In [13]:
zeros = np.zeros((2,3))
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [14]:
range_array = np.arange(0,10,2)
range_array

array([0, 2, 4, 6, 8])

In [15]:
random_array = np.random.randint(0,10, size=(3,5))
random_array

array([[9, 2, 8, 3, 0],
       [3, 9, 2, 9, 2],
       [9, 6, 0, 4, 9]])

In [16]:
random_array.size

15

In [17]:
random_array.shape

(3, 5)

In [18]:
random_array_2 = np.random.random((5,3))
random_array_2

array([[0.23061418, 0.26373203, 0.57576474],
       [0.38368686, 0.53553792, 0.15049785],
       [0.42203027, 0.62840276, 0.96270174],
       [0.38875724, 0.20124229, 0.73790934],
       [0.46473596, 0.22638593, 0.85579471]])

In [19]:
random_array_2.shape

(5, 3)

In [20]:
random_array_3 = np.random.rand(5,3)
random_array_3

array([[0.62355222, 0.02578783, 0.27662622],
       [0.74292513, 0.68771748, 0.31444388],
       [0.58053616, 0.35490056, 0.61875709],
       [0.28213179, 0.14370025, 0.13606198],
       [0.13403218, 0.77763898, 0.09458814]])

In [21]:
# Pseudo-random numbers
np.random.seed(seed=0)
random_array_4 = np.random.randint(10, size=(5,3))
random_array_4

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2],
       [4, 7, 6],
       [8, 8, 1]])

In [22]:
np.random.seed(seed=7)
random_array_5 = np.random.random((5,3))
random_array_5

array([[0.07630829, 0.77991879, 0.43840923],
       [0.72346518, 0.97798951, 0.53849587],
       [0.50112046, 0.07205113, 0.26843898],
       [0.4998825 , 0.67923   , 0.80373904],
       [0.38094113, 0.06593635, 0.2881456 ]])

## 3. Viewing arrays and matrices

In [23]:
np.unique(random_array_4)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [24]:
a2[1]

array([4, 5, 6])

In [25]:
a3[:2,:2,:2]

array([[[ 1,  2],
        [ 4,  5]],

       [[10, 11],
        [13, 14]]])

In [26]:
a4 = np.random.randint(10, size=(2,3,4,5))
a4

array([[[[3, 5, 8, 8, 7],
         [5, 0, 0, 2, 8],
         [9, 6, 4, 9, 7],
         [3, 3, 8, 3, 0]],

        [[1, 0, 0, 6, 7],
         [7, 9, 3, 0, 7],
         [7, 7, 0, 5, 4],
         [3, 1, 3, 1, 3]],

        [[4, 3, 1, 9, 5],
         [9, 1, 2, 3, 2],
         [2, 5, 7, 3, 0],
         [9, 9, 3, 4, 5]]],


       [[[3, 0, 4, 8, 6],
         [7, 2, 7, 3, 8],
         [6, 6, 5, 6, 5],
         [7, 1, 5, 4, 4]],

        [[9, 9, 0, 6, 2],
         [6, 8, 2, 4, 1],
         [6, 1, 5, 1, 6],
         [9, 8, 6, 5, 9]],

        [[7, 5, 4, 9, 6],
         [8, 1, 5, 5, 8],
         [3, 7, 7, 9, 4],
         [7, 5, 9, 6, 2]]]])

In [27]:
# Get the first 4 numbers of the inner most arrays
a4[:,:,:,:4]

array([[[[3, 5, 8, 8],
         [5, 0, 0, 2],
         [9, 6, 4, 9],
         [3, 3, 8, 3]],

        [[1, 0, 0, 6],
         [7, 9, 3, 0],
         [7, 7, 0, 5],
         [3, 1, 3, 1]],

        [[4, 3, 1, 9],
         [9, 1, 2, 3],
         [2, 5, 7, 3],
         [9, 9, 3, 4]]],


       [[[3, 0, 4, 8],
         [7, 2, 7, 3],
         [6, 6, 5, 6],
         [7, 1, 5, 4]],

        [[9, 9, 0, 6],
         [6, 8, 2, 4],
         [6, 1, 5, 1],
         [9, 8, 6, 5]],

        [[7, 5, 4, 9],
         [8, 1, 5, 5],
         [3, 7, 7, 9],
         [7, 5, 9, 6]]]])

In [28]:
a4[0][0]

array([[3, 5, 8, 8, 7],
       [5, 0, 0, 2, 8],
       [9, 6, 4, 9, 7],
       [3, 3, 8, 3, 0]])

## 4. Manipulating & comparing arrays

### Arithmetic

In [29]:
a1

array([1, 2, 3])

In [30]:
ones = np.ones(3)
ones

array([1., 1., 1.])

In [31]:
a1 + ones

array([2., 3., 4.])

In [32]:
a1 - ones

array([0., 1., 2.])

In [33]:
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [34]:
a1*a2

array([[ 1,  4,  9],
       [ 4, 10, 18]])

In [35]:
a1/ones

array([1., 2., 3.])

In [36]:
a2 // a1

array([[1, 1, 1],
       [4, 2, 2]])

In [37]:
a2 ** 2

array([[ 1,  4,  9],
       [16, 25, 36]])

In [38]:
np.add(a1, ones)

array([2., 3., 4.])

In [39]:
a1 % 2

array([1, 0, 1], dtype=int32)

In [40]:
np.exp(a1)

array([ 2.71828183,  7.3890561 , 20.08553692])

In [41]:
np.log(a1)

array([0.        , 0.69314718, 1.09861229])

### Aggregation

In [42]:
alist = [1,2,3]

In [43]:
sum(alist)

6

In [44]:
a1

array([1, 2, 3])

In [45]:
sum(a1)

6

In [46]:
np.sum(a1)

6

In [47]:
# create large numpy array
big_array = np.random.random(100000)
big_array[:10]

array([0.82845319, 0.94180927, 0.12814785, 0.23043067, 0.6591584 ,
       0.13247399, 0.22407864, 0.57486259, 0.16952372, 0.78223015])

In [48]:
%timeit sum(big_array)
%timeit np.sum(big_array)

5.17 ms ± 207 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
26.4 µs ± 475 ns per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [49]:
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [50]:
np.mean(a2)

3.5

In [51]:
np.max(a2)

6

In [52]:
np.std(a2)

1.707825127659933

In [53]:
np.var(a2)

2.9166666666666665

In [54]:
a2.shape

(2, 3)

In [55]:
a2.reshape(2,3,1)

array([[[1],
        [2],
        [3]],

       [[4],
        [5],
        [6]]])

In [56]:
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [57]:
a2_reshape = a2.reshape(2,3,1)
a2_reshape

array([[[1],
        [2],
        [3]],

       [[4],
        [5],
        [6]]])

In [58]:
a2_reshape * a3

array([[[  1,   2,   3],
        [  8,  10,  12],
        [ 21,  24,  27]],

       [[ 40,  44,  48],
        [ 65,  70,  75],
        [ 96, 102, 108]]])

In [59]:
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [60]:
a2.T

array([[1, 4],
       [2, 5],
       [3, 6]])

## Dot Product

In [61]:
np.random.seed(0)
m1 = np.random.randint(10, size=(5,3))
m2 = np.random.randint(10, size=(5,3))
m1

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2],
       [4, 7, 6],
       [8, 8, 1]])

In [62]:
m2

array([[6, 7, 7],
       [8, 1, 5],
       [9, 8, 9],
       [4, 3, 0],
       [3, 5, 0]])

In [63]:
# element wise multiplication
m1*m2

array([[30,  0, 21],
       [24,  7, 45],
       [27, 40, 18],
       [16, 21,  0],
       [24, 40,  0]])

In [64]:
# dot product
m3 = np.dot(m1.T, m2)
m3

array([[121, 114,  77],
       [153, 108,  80],
       [135,  69,  84]])

## Dot product example - nut butter sales

In [65]:
np.random.seed(0)
# number of jars sold
sales_amounts = np.random.randint(20, size=(5,3))
sales_amounts

array([[12, 15,  0],
       [ 3,  3,  7],
       [ 9, 19, 18],
       [ 4,  6, 12],
       [ 1,  6,  7]])

In [66]:
# create weekly sales DF
weekly_sales = pd.DataFrame(sales_amounts, index=["Mon", "Tue","Wed","Thu","Fri"], columns=["Almond", "Peanut", "Cashew"])
weekly_sales

Almond  Peanut  Cashew
Mon      12      15       0
Tue       3       3       7
Wed       9      19      18
Thu       4       6      12
Fri       1       6       7

In [67]:
# create prices arrays
prices = np.array([10, 8, 12])
prices

array([10,  8, 12])

In [69]:
# Create prices DF
butter_prices = pd.DataFrame(prices.reshape(1,3), index=["Price"], columns=["Almond", "Peanut", "Cashew"])
butter_prices

Almond  Peanut  Cashew
Price      10       8      12

In [70]:
# shapes not aligned so transpose
total_sales = prices.dot(sales_amounts.T)
total_sales

array([240, 138, 458, 232, 142])

In [71]:
# create daily_sales
daily_sales = butter_prices.dot(weekly_sales.T)
daily_sales

Mon  Tue  Wed  Thu  Fri
Price  240  138  458  232  142

In [72]:
weekly_sales["Total $"] = daily_sales.T
weekly_sales

Almond  Peanut  Cashew  Total $
Mon      12      15       0      240
Tue       3       3       7      138
Wed       9      19      18      458
Thu       4       6      12      232
Fri       1       6       7      142

### Comparison Operators

In [73]:
a1

array([1, 2, 3])

In [74]:
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [75]:
a1 > a2

array([[False, False, False],
       [False, False, False]])

In [77]:
bool_array = a1 >= a2
bool_array

array([[ True,  True,  True],
       [False, False, False]])

In [78]:
type(bool_array), bool_array.dtype

(numpy.ndarray, dtype('bool'))

In [79]:
a1 > 5

array([False, False, False])

In [81]:
a1 == a2

array([[ True,  True,  True],
       [False, False, False]])

## 5. sorting arrays

In [85]:
random_array = np.random.randint(10, size=(3, 5))
random_array

array([[0, 2, 3, 8, 1],
       [3, 3, 3, 7, 0],
       [1, 9, 9, 0, 4]])

In [86]:
np.sort(random_array)

array([[0, 1, 2, 3, 8],
       [0, 3, 3, 3, 7],
       [0, 1, 4, 9, 9]])

In [87]:
np.argsort(random_array)

array([[0, 4, 1, 2, 3],
       [4, 0, 1, 2, 3],
       [3, 0, 4, 1, 2]], dtype=int64)

In [88]:
a1

array([1, 2, 3])

In [89]:
np.argsort(a1)

array([0, 1, 2], dtype=int64)

In [90]:
np.argmin(a1)

0

In [91]:
np.argmax(a1)

2

In [94]:
random_array

array([[0, 2, 3, 8, 1],
       [3, 3, 3, 7, 0],
       [1, 9, 9, 0, 4]])

In [95]:
np.argmax(random_array, axis=0)

array([1, 2, 2, 0, 2], dtype=int64)

## 6. practical example

<img src="images/panda.png"/>

In [101]:
# turn image into numpy array
from matplotlib.image import imread
panda = imread("images/panda.png")
print(type(panda))

<class 'numpy.ndarray'>


In [102]:
panda

array([[[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       [[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       [[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       ...,

       [[0.13333334, 0.07450981, 0.05490196],
        [0.12156863, 0.0627451 , 0.04313726],
        [0.10980392, 0

In [103]:
panda.size, panda.shape, panda.ndim

(24465000, (2330, 3500, 3), 3)

In [105]:
panda[:5]

array([[[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       [[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       [[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       [[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.

<img src="images/car-photo.png"/>

In [106]:
car = imread("images/car-photo.png")

<img src="images/dog-photo.png"/>

In [108]:
dog = imread("images/dog-photo.png")