In [1]:
import numpy as np

## DataTypes & Attributes 

In [2]:
# NumPy's main datatype is ndarray
a1 = np.array([1,2,3])
a1

array([1, 2, 3])

In [3]:
type(a1)

numpy.ndarray

In [4]:
a2 = np.array([[1,2,3], 
              [4,5,6]])
a3 = np.array([
    [
        [1,2,3], 
        [4,5,6],
        [7,8,9]
    ],
    [
        [10,11,12], 
        [13,14,15],
        [16,17,18]
    ]
])
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [5]:
a3.shape

(2, 3, 3)

In [6]:
a3.ndim

3

In [7]:
a3.dtype

dtype('int32')

In [8]:
# Create a dataframe from numpy array
import pandas as pd
df = pd.DataFrame(a2)
df

0  1  2
0  1  2  3
1  4  5  6

## 2. create arrays

In [9]:
sample_array = np.array([1,2,3])
sample_array

array([1, 2, 3])

In [10]:
sample_array.dtype

dtype('int32')

In [11]:
ones = np.ones((2,3))
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [12]:
ones.dtype

dtype('float64')

In [14]:
zeros = np.zeros((2,3))
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [15]:
range_array = np.arange(0,10,2)
range_array

array([0, 2, 4, 6, 8])

In [16]:
random_array = np.random.randint(0,10, size=(3,5))
random_array

array([[6, 2, 1, 0, 3],
       [9, 3, 6, 9, 5],
       [2, 5, 1, 9, 2]])

In [17]:
random_array.size

15

In [18]:
random_array.shape

(3, 5)