In [19]:
import numpy as np

## DataTypes & Attributes 

In [20]:
# NumPy's main datatype is ndarray
a1 = np.array([1,2,3])
a1

array([1, 2, 3])

In [21]:
type(a1)

numpy.ndarray

In [22]:
a2 = np.array([[1,2,3], 
              [4,5,6]])
a3 = np.array([
    [
        [1,2,3], 
        [4,5,6],
        [7,8,9]
    ],
    [
        [10,11,12], 
        [13,14,15],
        [16,17,18]
    ]
])
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [23]:
a3.shape

(2, 3, 3)

In [24]:
a3.ndim

3

In [25]:
a3.dtype

dtype('int32')

In [26]:
# Create a dataframe from numpy array
import pandas as pd
df = pd.DataFrame(a2)
df

0  1  2
0  1  2  3
1  4  5  6

## 2. create arrays

In [27]:
sample_array = np.array([1,2,3])
sample_array

array([1, 2, 3])

In [28]:
sample_array.dtype

dtype('int32')

In [29]:
ones = np.ones((2,3))
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [30]:
ones.dtype

dtype('float64')

In [31]:
zeros = np.zeros((2,3))
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [32]:
range_array = np.arange(0,10,2)
range_array

array([0, 2, 4, 6, 8])

In [33]:
random_array = np.random.randint(0,10, size=(3,5))
random_array

array([[3, 5, 8, 0, 2],
       [3, 9, 2, 1, 8],
       [6, 4, 6, 0, 5]])

In [34]:
random_array.size

15

In [35]:
random_array.shape

(3, 5)

In [37]:
random_array_2 = np.random.random((5,3))
random_array_2

array([[0.43232092, 0.06546495, 0.8661238 ],
       [0.18681055, 0.52031981, 0.91758752],
       [0.19532583, 0.74388209, 0.2146677 ],
       [0.21677775, 0.74590949, 0.45203365],
       [0.16629642, 0.32909511, 0.64631837]])

In [38]:
random_array_2.shape

(5, 3)

In [39]:
random_array_3 = np.random.rand(5,3)
random_array_3

array([[0.75435408, 0.15647199, 0.63717708],
       [0.13307222, 0.0597032 , 0.4405509 ],
       [0.47519229, 0.32017455, 0.04858116],
       [0.41476331, 0.34395409, 0.23689626],
       [0.16859243, 0.95726458, 0.71584593]])

In [46]:
# Pseudo-random numbers
np.random.seed(seed=0)
random_array_4 = np.random.randint(10, size=(5,3))
random_array_4

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2],
       [4, 7, 6],
       [8, 8, 1]])

In [47]:
np.random.seed(seed=7)
random_array_5 = np.random.random((5,3))
random_array_5

array([[0.07630829, 0.77991879, 0.43840923],
       [0.72346518, 0.97798951, 0.53849587],
       [0.50112046, 0.07205113, 0.26843898],
       [0.4998825 , 0.67923   , 0.80373904],
       [0.38094113, 0.06593635, 0.2881456 ]])

## 3. Viewing arrays and matrices

In [48]:
np.unique(random_array_4)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [49]:
a2[1]

array([4, 5, 6])

In [50]:
a3[:2,:2,:2]

array([[[ 1,  2],
        [ 4,  5]],

       [[10, 11],
        [13, 14]]])

In [51]:
a4 = np.random.randint(10, size=(2,3,4,5))
a4

array([[[[3, 5, 8, 8, 7],
         [5, 0, 0, 2, 8],
         [9, 6, 4, 9, 7],
         [3, 3, 8, 3, 0]],

        [[1, 0, 0, 6, 7],
         [7, 9, 3, 0, 7],
         [7, 7, 0, 5, 4],
         [3, 1, 3, 1, 3]],

        [[4, 3, 1, 9, 5],
         [9, 1, 2, 3, 2],
         [2, 5, 7, 3, 0],
         [9, 9, 3, 4, 5]]],


       [[[3, 0, 4, 8, 6],
         [7, 2, 7, 3, 8],
         [6, 6, 5, 6, 5],
         [7, 1, 5, 4, 4]],

        [[9, 9, 0, 6, 2],
         [6, 8, 2, 4, 1],
         [6, 1, 5, 1, 6],
         [9, 8, 6, 5, 9]],

        [[7, 5, 4, 9, 6],
         [8, 1, 5, 5, 8],
         [3, 7, 7, 9, 4],
         [7, 5, 9, 6, 2]]]])

In [53]:
# Get the first 4 numbers of the inner most arrays
a4[:,:,:,:4]

array([[[[3, 5, 8, 8],
         [5, 0, 0, 2],
         [9, 6, 4, 9],
         [3, 3, 8, 3]],

        [[1, 0, 0, 6],
         [7, 9, 3, 0],
         [7, 7, 0, 5],
         [3, 1, 3, 1]],

        [[4, 3, 1, 9],
         [9, 1, 2, 3],
         [2, 5, 7, 3],
         [9, 9, 3, 4]]],


       [[[3, 0, 4, 8],
         [7, 2, 7, 3],
         [6, 6, 5, 6],
         [7, 1, 5, 4]],

        [[9, 9, 0, 6],
         [6, 8, 2, 4],
         [6, 1, 5, 1],
         [9, 8, 6, 5]],

        [[7, 5, 4, 9],
         [8, 1, 5, 5],
         [3, 7, 7, 9],
         [7, 5, 9, 6]]]])

In [55]:
a4[0][0]

array([[3, 5, 8, 8, 7],
       [5, 0, 0, 2, 8],
       [9, 6, 4, 9, 7],
       [3, 3, 8, 3, 0]])

## 4. Manipulating & comparing arrays

### Arithmetic

In [56]:
a1

array([1, 2, 3])

In [59]:
ones = np.ones(3)
ones

array([1., 1., 1.])

In [60]:
a1 + ones

array([2., 3., 4.])

In [61]:
a1 - ones

array([0., 1., 2.])

In [62]:
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [63]:
a1*a2

array([[ 1,  4,  9],
       [ 4, 10, 18]])

In [64]:
a1/ones

array([1., 2., 3.])

In [65]:
a2 // a1

array([[1, 1, 1],
       [4, 2, 2]])

In [66]:
a2 ** 2

array([[ 1,  4,  9],
       [16, 25, 36]])

In [67]:
np.add(a1, ones)

array([2., 3., 4.])

In [68]:
a1 % 2

array([1, 0, 1], dtype=int32)

In [69]:
np.exp(a1)

array([ 2.71828183,  7.3890561 , 20.08553692])

In [70]:
np.log(a1)

array([0.        , 0.69314718, 1.09861229])

### Aggregation

In [71]:
alist = [1,2,3]

In [72]:
sum(alist)

6

In [73]:
a1

array([1, 2, 3])

In [74]:
sum(a1)

6

In [75]:
np.sum(a1)

6

In [77]:
# create large numpy array
big_array = np.random.random(100000)
big_array[:10]

array([0.14629848, 0.02679954, 0.43896203, 0.21919162, 0.50924549,
       0.63324985, 0.09514576, 0.74406295, 0.24829088, 0.96799755])

In [78]:
%timeit sum(big_array)
%timeit np.sum(big_array)

5.01 ms ± 111 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
25.4 µs ± 396 ns per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [79]:
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [80]:
np.mean(a2)

3.5

In [81]:
np.max(a2)

6

In [82]:
np.std(a2)

1.707825127659933

In [83]:
np.var(a2)

2.9166666666666665

In [84]:
a2.shape

(2, 3)

In [87]:
a2.reshape(2,3,1)

array([[[1],
        [2],
        [3]],

       [[4],
        [5],
        [6]]])

In [86]:
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [88]:
a2_reshape = a2.reshape(2,3,1)
a2_reshape

array([[[1],
        [2],
        [3]],

       [[4],
        [5],
        [6]]])

In [89]:
a2_reshape * a3

array([[[  1,   2,   3],
        [  8,  10,  12],
        [ 21,  24,  27]],

       [[ 40,  44,  48],
        [ 65,  70,  75],
        [ 96, 102, 108]]])

In [90]:
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [91]:
a2.T

array([[1, 4],
       [2, 5],
       [3, 6]])

## Dot Product

In [93]:
np.random.seed(0)
m1 = np.random.randint(10, size=(5,3))
m2 = np.random.randint(10, size=(5,3))
m1

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2],
       [4, 7, 6],
       [8, 8, 1]])

In [94]:
m2

array([[6, 7, 7],
       [8, 1, 5],
       [9, 8, 9],
       [4, 3, 0],
       [3, 5, 0]])

In [95]:
# element wise multiplication
m1*m2

array([[30,  0, 21],
       [24,  7, 45],
       [27, 40, 18],
       [16, 21,  0],
       [24, 40,  0]])

In [99]:
# dot product
m3 = np.dot(m1.T, m2)
m3

array([[121, 114,  77],
       [153, 108,  80],
       [135,  69,  84]])